src/routes/books/libgen.ts, src/routes/comics/getComics.ts, src/routes/comics/index.ts, src/routes/light-novels/readlightnovels.ts
Fixed the getComics /s route and the comics /s route.
=> getComics route fix

yarn.lock
=> chore: bump consumet.ts

yarn.lock
Reverts consumet/consumet-api#117
=> revert "chore(deps): lock file maintenance"

package.json, yarn.lock
Reverts consumet/api.consumet.org#207
=> Revert "fix(deps): update dependency node-fetch to v3"

src/routes/meta/anilist.ts
fixed cache, pages not being stored
changes made by: @illusionTBA
=> fixed cache, pages not being stored

README.md, vercel.json
This will allow users deploy to vercel.
=> Deploy to vercel button

src/routes/movies/flixhq.ts
ignore the double commits by git messed up and it just ended up like that
=> adds trending route to flixhq

package.json, yarn.lock
=> bump consumet ver

src/utils/m3u8-proxy.ts
add m3u8 proxy that fixes absolute paths in m3u8 files for example from crunchy
=> fix Chayce errors for m3u8 proxy

package-lock.json, package.json, src/utils/image-proxy.ts, yarn.lock
Fixed image proxy and package.json.
=> Fix image-proxy and update package.json

src/utils/image-proxy.ts
Fixed issue with image proxy not working.
=> Fix image-proxy.ts

src/routes/anime/zoro.ts
Fix zoro recent-episodes route and added new routes such top-airing, most-popular, most-favorite, latest-completed, recent-added, top-upcoming
=> feat: zoro extra routes

src/routes/anime/gogoanime.ts
What kind of change does this PR introduce?
Add list all anime from A-Z route. Utilizes function added from https://github.com/consumet/consumet.ts/pull/466
=> feat(gogoanime): Add list all anime route

src/routes/anime/gogoanime.ts
This is just an edit of https://github.com/consumet/api.consumet.org/pull/573. Just made redis optional here
=> feat(gogoanime): Add redis cache

src/routes/movies/flixhq.ts
To avoid confusion following route has been added to info page
=> Added routes to flixhq info page

src/routes/anime/gogoanime.ts
Add route for added function on https://github.com/consumet/consumet.ts/commit/f4c908becbbda89386c5dba0c75c4fb2a6e8d6db in consumet.ts
=> feat(gogoanime): get direct download links from download url

src/routes/anime/zoro.ts
Add new routes for anime schedule, studio, spotlight, and search suggestions for zoro
=>  New routes in zoro provider

src/routes/meta/anilist.ts
=> fix: adapter is not a function error

src/routes/meta/anilist.ts, src/routes/movies/dramacool.ts
- Added routes for Anilist staff info and popular dramas from Dramacool.
=> feat:  Add routes for Anilist staff info by ID and popular dramas from Dramacool

src/routes/movies/dramacool.ts
=> Add popular to routes

src/routes/meta/anilist.ts
Introduced a new query parameter `dub` to fetch dubbed sources and updated the caching and fetching logic to account for this parameter.
=> feat(anilist): Enhance episode source fetching with dub/sub support
